# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/debian10"
  config.vm.box_check_update = true
  config.vm.hostname = "setuptalk.local"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vm|
    vm.gui = false
    vm.cpus = 2
    vm.memory = "512"
    vm.linked_clone = true

    vm.customize ["modifyvm", :id, "--pae", "on"]
  end

  config.vm.network :forwarded_port, id: "mongodb", guest: 27017, host: 27017

  # this will ensure ansible provisioning will work.
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "../", "/code", owner: "vagrant", group: "vagrant", mount_options: ["dmode=755", "fmode=644"]


  # follow steps in playbook to setup the development environment
  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "ansible/site.yml"
    ansible.galaxy_role_file = "ansible/requirements.yml"
    ansible.galaxy_roles_path = "ansible/roles/vendors"
    ansible.limit = "all"
  end
end

# vim: set ts=2 sw=2 et ft=ruby #
