---
- name: Setup Talk WebApp services machine
  hosts: all
  become: true

  vars:
    common_timezone: "America/New_York"

    # in case there are roles that install/update non-global
    # configuration should look at `nonroot_user` var to
    # find out who is the default user in the system
    nonroot_user: "vagrant"
    nonroot_user_home: "/home/vagrant"

    docker_compose_version: "1.26.0"
    docker_users: [ "vagrant" ]

  roles:
    - geerlingguy.docker

  tasks:
    - name: Start docker-compose services.
      command: "/usr/local/bin/docker-compose up -d"
      args:
        chdir: /code
